### ISSUE TITLE
Help wanted: cross compile adb for arm

### ISSUE THREAD

**Issue by kmahyyg** [qmfrederik/adb-win64#1]
I 've STFW a lot.Need help.

I want to cross compile adb for my Raspberry Pi(armv7) .How should I port this repo's Makefile?

And also,if I want to bring back ADB for device-on-target , How can I do it?

Workspace: Ubuntu 16.04.2 LTS x86-64 with ndk installed and also other needed dependencies

**Comment by qmfrederik** [comment]
@kmahyyg I'm sorry, but this repository is about cross-compiling adb for 64-bit Windows, not Linux.
